### ISSUE TITLE
Import problem in 4.1.0

### ISSUE THREAD

**Issue by rybaczewa** [slevithan/xregexp#227]
Using xregexp as a dependency in node app. After upgrading to 4.1.0, there's an import problem:

```js
Error: Cannot find module '../../tools/output/blocks'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/(...)/node_modules/xregexp/lib/addons/unicode-blocks.js:7:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by AnimaLupi** [comment]
I confirm that. The tools directory isn't included in npm package.

**Comment by slevithan** [comment]
I've published v4.1.1 to address this but it looks like it's still failing. @josephfrazier do you know what's going wrong here?

**Comment by josephfrazier** [comment]
Thanks for the quick fix, @slevithan! I can't believe I didn't catch that earlier...

I tried to reproduce the issue in an empty directory by running the following, but it appeared to work as expected:

```bash
cd $(mktemp -d) && yarn add xregexp webpack && echo "import XRegExp from 'xregexp'; console.log(XRegExp)" > t.js && yarn webpack t.js out.js && node out.js
```

You can try it online here: https://codesandbox.io/s/xvwjv8nyno

As of v4.1.1, the `tools` directory is published (https://unpkg.com/xregexp@4.1.1/tools/output/), so the problem must be something else. Can you describe how you're testing it?

**Comment by AnimaLupi** [comment]
Using 4.1.1 I'm able to build and include the lib in my project without any further issue... Thanks!

**Comment by slevithan** [comment]
Thanks @josephfrazier for confirming its working and sharing your test. :D And thanks @mathiasbynens for cleaning up after me by removing `tools/scripts`.

@josephfrazier, sorry for the confusion. This was user error by me while in a rush out the door.

**Comment by josephfrazier** [comment]
It's all good, the bug was originally my fault anyway, so I was anxious to see it fixed. Thanks again!

**Comment by josephfrazier** [comment]
Oh @slevithan, we should probably `npm deprecate` v4.1.0, so anyone who happens to install it will get a message to upgrade. See here for details: https://docs.npmjs.com/cli/deprecate

**Comment by slevithan** [comment]
Thanks for the pointer. Done!

**Comment by josephfrazier** [comment]
Cheers!
