### ISSUE TITLE
"Cannot find module ..." Issues after update to 3.2.0?

### ISSUE THREAD

**Issue by cainvommars** [slevithan/xregexp#198]
node v6.10.2
npm 5.0.4

```javascript
Error: Cannot find module './xregexp' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/unicode-properties' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/matchrecursive' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/build' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/unicode-categories' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/unicode-scripts' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/unicode-base' from '/var/www/nodefrontend/current/node_modules/xregexp'
Error: Cannot find module './addons/unicode-blocks' from '/var/www/nodefrontend/current/node_modules/xregexp'
```

usage:
```javascript
import xregexp from 'xregexp';
...
const unicodeWord = xregexp('[\\p{L}\\.\\-\\ ]{1,}');
return unicodeWord.test(str);
...
```

The installed npm package contains a xregexp-all.js on the root level which is mentioned in the package.json as "main".
However this file tries to require some modules like this:
```javascript
...
},{}],8:[function(require,module,exports){
var XRegExp = require('./xregexp');

require('./addons/build')(XRegExp);
require('./addons/matchrecursive')(XRegExp);
require('./addons/unicode-base')(XRegExp);
require('./addons/unicode-blocks')(XRegExp);
require('./addons/unicode-categories')(XRegExp);
require('./addons/unicode-properties')(XRegExp);
require('./addons/unicode-scripts')(XRegExp);
...
```

These requires are broken because the actual files are stored in src/.
So for this particular file the following would be correct.

```javascript
...
},{}],8:[function(require,module,exports){
var XRegExp = require('./src/xregexp');

require('./src/addons/build')(XRegExp);
require('./src/addons/matchrecursive')(XRegExp);
require('./src/addons/unicode-base')(XRegExp);
require('./src/addons/unicode-blocks')(XRegExp);
require('./src/addons/unicode-categories')(XRegExp);
require('./src/addons/unicode-properties')(XRegExp);
require('./src/addons/unicode-scripts')(XRegExp);
...
```

Something is fishy here. Did the packaging for the release went wrong? Am I using the module wrong?

**Comment by knu** [comment]
I'm seeing the same problem.  Seems Browserify fails to locate the module "xregexp", and the error message reads`Error: Cannot find module 'xregexp' from ...`.

I'm not sure if the current value of `main` in package.json makes sense at all: https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/package.json#L18
Is `./lib` loadable?

**Comment by vasyas** [comment]
The same for React-Native

**Comment by epsil** [comment]
It appears that v2.0.0 is the last version that works with Browserify.

**Comment by slevithan** [comment]
Will accept pull requests that address this.

**Comment by webmobiles** [comment]
the problem is not the pluggin is not imported?

the right is ?
import addons/unicode/unicode-base ?

**Comment by webmobiles** [comment]
not really needed 'import unicode-base' on my react app, 
it's working ok, here my code:

```
import XRegExp from 'xregexp';
export const alpha = (value) => {
  const unicodeWord = XRegExp('^\\p{L}+$');
  return (!unicodeWord.test (value) ? 'validator.alpha' : '');
};
```

**Comment by josephfrazier** [comment]
I was able to reproduce this as follows:

```bash
cd $(mktemp -d)
yarn add xregexp browserify
yarn browserify node_modules/xregexp
```

@knu:

> I'm not sure if the current value of `main` in package.json makes sense at all:
> https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/package.json#L18
> Is `./lib` loadable?

Note that in v3.2.0, `main` points to `xregexp-all.js`, as indicated by @cainvommars (you can see [the file on unpkg](https://unpkg.com/xregexp@3.2.0/package.json)). It was changed to `./lib` as part of https://github.com/slevithan/xregexp/pull/182. I believe this fixed the issue, as the following currently works on the master branch:

```bash
yarn # to build the files in ./lib
yarn browserify .
```

I'm hoping to release a new version to address this: https://github.com/slevithan/xregexp/pull/205
